theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
rulers = [80]

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode"]
center = ["diagnostics", "file-name", "file-modification-indicator"]
right = ["workspace-diagnostics", "version-control", "spinner"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
